# Generated by Django 4.0.4 on 2022-04-13 11:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('TaskApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskstable',
            name='TaskID',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.CreateModel(
            name='TaskStatusTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TStatus', models.CharField(choices=[('NotStarted', 'NotStarted'), ('InProgress', 'InProgress'), ('Completed', 'Completed')], max_length=255)),
                ('TaskID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TaskApp.taskstable')),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
